### ISSUE TITLE
Cannot preview the plots in the analysis notebook

### ISSUE THREAD

**Issue by ppoply** [cricksmaidiene/whatsapp_chat_analysis#1]
Hi Eshwaran, hope you are doing well. 

I was trying to preview the analysis notebook through GitHub. Unfortunately, I'm unable to view any of the analysis plots/graphs present in the notebook. 

For reference:

![image](https://user-images.githubusercontent.com/34216657/150993886-94b12230-32e6-4e5e-8c43-87d90223ad92.png)

Could you please update the notebook so that I'm able to view the plots ?

Cheers,
Parth

**Comment by cricksmaidiene** [comment]
@ppoply 

The graphs used for the notebook are from [Plotly](https://plotly.com/python/). Jupyter does not natively render plotly graphs the same way it does for something like Matplotlib. You can always clone the repo and install the required dependencies to show plotly graphs. I've listed this in the [README file](https://github.com/cricksmaidiene/whatsapp_chat_analysis/blob/main/README.md) in the "Setting Up" section. 

Either of the following are the jupyter requirements & versions: 
* `jupyterlab==2.2.6` requires `jupyter labextension install jupyterlab-plotly@4.14.3`, in turn requires `nodejs >= 10.0`. Install nodejs with `conda install nodejs -c conda-forge --repodata-fn=repodata.json`
* `jupyter notebook==6.2.0`

I believe I tested this on JupyterLab, so it should work fine there. If you have issues with it showing on Jupyter Notebook then do let me know.
